name: media_tool_ffmpeg
description: FFmpeg based implementation of media_tool for iOS, macOS and Android
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

flutter:
  plugin:
    implements: media_tool
    platforms:
      android:
        dartPluginClass: MediaToolFFmpeg
      ios:
        dartPluginClass: MediaToolFFmpeg
      macos:
        dartPluginClass: MediaToolFFmpeg

dependencies:
  ffmpeg_kit_flutter_full_gpl: ">=6.0.0 <7.0.0"
  flutter:
    sdk: flutter
  media_tool_platform_interface:
    path: ../media_tool_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # mocktail: ">=0.3.0 <2.0.0"
  test: ">=1.19.2 <2.0.0"
  very_good_analysis: ">=4.0.0 <6.0.0"
