name: media_tool_ffmpeg
description: FFmpeg based implementation of media_tool for iOS, macOS and Android
homepage: https://github.com/starkdmi/media_tool_flutter
repository: https://github.com/starkdmi/media_tool_ffmpeg
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"
  # Flutter versions prior to 3.7 did not support the sharedDarwinSource option.
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: media_tool
    platforms:
      android:
        dartPluginClass: MediaToolFFmpeg
      ios:
        dartPluginClass: MediaToolFFmpeg
      macos:
        dartPluginClass: MediaToolFFmpeg

dependencies:
  ffmpeg_kit_flutter_full_gpl: ">=6.0.0 <7.0.0"
  flutter:
    sdk: flutter
  media_tool_platform_interface: ">=0.1.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # mocktail: ">=0.3.0 <2.0.0"
  test: ">=1.19.2 <2.0.0"
  very_good_analysis: ">=4.0.0 <6.0.0"
